baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo Basic Site'
copyright = 'All rights reserved'
paginate = 2
summaryLength = 20

[menu]
#[[menu.main]]
#  name = 'Home'
#  url = '/'
#  weight = 10
[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 20
[[menu.main]]
  name = 'About'
  url = '/page/about'
  weight = 40
[[menu.main]]
  name = 'GitHub'
  url = 'http://www.github.com/'
  weight = 99

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # change to 'true' if you need to render raw HTML within your markdown content
      unsafe = true

[params]
slogan = 'Super Fast!'
